### PR TITLE
Some edits from me

### PR DESCRIPTION
**Pull request by dfm**
I've started editing the paper a bit. Overall, it seems good but I think that a lot of the language is too strong. @davidwhogg keeps saying "provably correct" but it's never demonstrated convincingly. I don't think we want to prove this so I'd just cut this terminology entirely.

Feel free to merge this but I'll keep editing.

### CODE REVIEW

**Comment by davidwhogg** [comment]
I agree, but if it isn't for our demonstrable correctness, why not just use DNEST?

**Comment by dfm** [comment]
Exactly. Convince me :-)

**Comment by adrn** [comment]
@dfm I made an issue that I think explains your concerns #32

**Comment by adrn** [comment]
@dfm Also, RE: "verify the likelihood function is unimodal" and your comment. Just to clarify, we mean that if you have many, many precise observations, your likelihood should be unimodal. I can't tell if your point is that this statement is incorrect or if you are thinking about data sets with only few observations.

**Comment by dfm** [comment]
I just meant that your data will need to have _infinite_ signal-to-noise and be very precisely sampled to actually be perfectly unimodal. There's a definition of "unimodal enough" that's missing. For example, at the edge cases, different realizations of the simple MC will come to different conclusions about whether or not a posterior is unimodal. I think that the language is a little too strong currently.

**Comment by adrn** [comment]
Yea, got it!

**Pull request merged**
